### ISSUE TITLE
JSFoo'16: Dan Abramov as Guest Speaker

### ISSUE THREAD

**Issue by geraldchecka** [hasgeek/jsfoo#9]
Dan Abramov is remembered with many names as "the redux guy", 'the react hotloader guy" etc... He has made significant contributions to the React community. As JSFoo has a custom of inviting guest speakers for its events, I suggest his name.
More about him can be found on github @gaearon

**Comment by hearsid** [comment]
+1

**Comment by jace** [comment]
We asked Dan but he's vacationing in Greece on the JSFoo dates and so can't make it.

**Comment by geraldchecka** [comment]
:-(
